const { spawnSync } = require('child_process');
const path = require('path');
function call(name,args){ const p = spawnSync(process.execPath,[path.resolve(__dirname,'..','..','examples','mcp-n8n-server.js'),'--once',name,JSON.stringify(args||{})],{encoding:'utf8',env:{...process.env,N8N_MCP_DRY_RUN:'1'}}); if(p.status!==0) throw new Error('Call failed:'+p.stderr); return JSON.parse(p.stdout); }
(async()=>{ try {
  try { const res = call("n8n.v1.Audit.post__audit", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Audit.post__audit: '+e.message); }
  try { const res = call("n8n.v1.Credential.post__credentials", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Credential.post__credentials: '+e.message); }
  try { const res = call("n8n.v1.Credential.deleteCredential", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Credential.deleteCredential: '+e.message); }
  try { const res = call("n8n.v1.Credential.get__credentials_schema__credentialTypeName_", {"credentialTypeName":"credentialTypeName"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Credential.get__credentials_schema__credentialTypeName_: '+e.message); }
  try { const res = call("n8n.v1.Execution.get__executions", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Execution.get__executions: '+e.message); }
  try { const res = call("n8n.v1.Execution.get__executions__id_", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Execution.get__executions__id_: '+e.message); }
  try { const res = call("n8n.v1.Execution.delete__executions__id_", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Execution.delete__executions__id_: '+e.message); }
  try { const res = call("n8n.v1.Tags.post__tags", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Tags.post__tags: '+e.message); }
  try { const res = call("n8n.v1.Tags.get__tags", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Tags.get__tags: '+e.message); }
  try { const res = call("n8n.v1.Tags.get__tags__id_", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Tags.get__tags__id_: '+e.message); }
  try { const res = call("n8n.v1.Tags.delete__tags__id_", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Tags.delete__tags__id_: '+e.message); }
  try { const res = call("n8n.v1.Tags.put__tags__id_", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Tags.put__tags__id_: '+e.message); }
  try { const res = call("n8n.v1.Workflow.post__workflows", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Workflow.post__workflows: '+e.message); }
  try { const res = call("n8n.v1.Workflow.get__workflows", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Workflow.get__workflows: '+e.message); }
  try { const res = call("n8n.v1.Workflow.get__workflows__id_", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Workflow.get__workflows__id_: '+e.message); }
  try { const res = call("n8n.v1.Workflow.delete__workflows__id_", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Workflow.delete__workflows__id_: '+e.message); }
  try { const res = call("n8n.v1.Workflow.put__workflows__id_", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Workflow.put__workflows__id_: '+e.message); }
  try { const res = call("n8n.v1.Workflow.post__workflows__id__activate", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Workflow.post__workflows__id__activate: '+e.message); }
  try { const res = call("n8n.v1.Workflow.post__workflows__id__deactivate", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Workflow.post__workflows__id__deactivate: '+e.message); }
  try { const res = call("n8n.v1.Workflow.put__workflows__id__transfer", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Workflow.put__workflows__id__transfer: '+e.message); }
  try { const res = call("n8n.v1.Workflow.put__credentials__id__transfer", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Workflow.put__credentials__id__transfer: '+e.message); }
  try { const res = call("n8n.v1.Workflow.get__workflows__id__tags", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Workflow.get__workflows__id__tags: '+e.message); }
  try { const res = call("n8n.v1.Workflow.put__workflows__id__tags", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Workflow.put__workflows__id__tags: '+e.message); }
  try { const res = call("n8n.v1.User.get__users", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.User.get__users: '+e.message); }
  try { const res = call("n8n.v1.User.post__users", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.User.post__users: '+e.message); }
  try { const res = call("n8n.v1.User.get__users__id_", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.User.get__users__id_: '+e.message); }
  try { const res = call("n8n.v1.User.delete__users__id_", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.User.delete__users__id_: '+e.message); }
  try { const res = call("n8n.v1.User.patch__users__id__role", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.User.patch__users__id__role: '+e.message); }
  try { const res = call("n8n.v1.SourceControl.post__source-control_pull", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.SourceControl.post__source-control_pull: '+e.message); }
  try { const res = call("n8n.v1.Variables.post__variables", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Variables.post__variables: '+e.message); }
  try { const res = call("n8n.v1.Variables.get__variables", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Variables.get__variables: '+e.message); }
  try { const res = call("n8n.v1.Variables.delete__variables__id_", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Variables.delete__variables__id_: '+e.message); }
  try { const res = call("n8n.v1.Variables.put__variables__id_", {"id":"id"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Variables.put__variables__id_: '+e.message); }
  try { const res = call("n8n.v1.Projects.post__projects", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Projects.post__projects: '+e.message); }
  try { const res = call("n8n.v1.Projects.get__projects", {}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Projects.get__projects: '+e.message); }
  try { const res = call("n8n.v1.Projects.delete__projects__projectId_", {"projectId":"projectId"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Projects.delete__projects__projectId_: '+e.message); }
  try { const res = call("n8n.v1.Projects.put__projects__projectId_", {"projectId":"projectId"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Projects.put__projects__projectId_: '+e.message); }
  try { const res = call("n8n.v1.Projects.post__projects__projectId__users", {"projectId":"projectId"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Projects.post__projects__projectId__users: '+e.message); }
  try { const res = call("n8n.v1.Projects.delete__projects__projectId__users__userId_", {"projectId":"projectId","userId":"userId"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Projects.delete__projects__projectId__users__userId_: '+e.message); }
  try { const res = call("n8n.v1.Projects.patch__projects__projectId__users__userId_", {"projectId":"projectId","userId":"userId"}); if (!res || typeof res !== 'object') throw new Error('no result'); if (!('dryRun' in res)) throw new Error('not dry-run'); } catch(e){ throw new Error('tool failed: n8n.v1.Projects.patch__projects__projectId__users__userId_: '+e.message); }
  console.log('Dry-run OK for tools:', '40');
  process.exit(0);
} catch (e) { console.error('UNIT FAILED:', e.message); process.exit(1);} })();